#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
SRC_DIR=${REPO_ROOT}/
cd "${SRC_DIR}"

if [[ -z "${IMAGE_PREFIX:-}" ]]; then
  IMAGE_PREFIX=""
fi
echo "Building images with prefix ${IMAGE_PREFIX}"

if [[ -z "${TAG:-}" ]]; then
  TAG=latest
fi

if [[ -z "${BUILDX_ARGS:-}" ]]; then
  BUILDX_ARGS="--load"
fi

docker buildx build ${BUILDX_ARGS} \
    -f images/kubectl-ai/Dockerfile \
    -t ${IMAGE_PREFIX}kubectl-ai:${TAG} \
    --progress=plain .
