#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
SRC_DIR=${REPO_ROOT}/modelserving
cd "${SRC_DIR}"

mkdir -p .cache

# TODO Verify checksum
if [[ ! -f .cache/gemma-3-12b-it-Q4_K_M.gguf ]]; then
  echo "Downloading gemma-3-12b-it-Q4_K_M.gguf"
  wget https://huggingface.co/unsloth/gemma-3-12b-it-GGUF/resolve/main/gemma-3-12b-it-Q4_K_M.gguf?download=true -O .cache/gemma-3-12b-it-Q4_K_M.gguf
fi